package com.uade.backendgestionbd2.util;

public enum SkillLevel {

    BACKEND_JUNIOR,
    BACKEND_MID,
    BACKEND_SENIOR,
    FRONTEND_JUNIOR,
    FRONTEND_MID,
    FRONTEND_SENIOR,
    FULLSTACK_JUNIOR,
    FULLSTACK_MID,
    FULLSTACK_SENIOR,
    DEVOPS_JUNIOR,
    DEVOPS_MID,
    DEVOPS_SENIOR,

}
